name: Build and Deploy Streamlit App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Debug working directory
      run: |
        pwd
        ls -la
        
    - name: Create data directory with full path
      run: |
        mkdir -p "$GITHUB_WORKSPACE/data"
        
    - name: Build Docker image
      run: |
        docker build -t personal-logs:latest .
        
    - name: Stop existing container
      run: |
        docker stop personal-logs || true
        docker rm personal-logs || true
      continue-on-error: true
        
    - name: Run Docker container
      run: |
        docker run -d \
          --name personal-logs \
          --restart unless-stopped \
          -v "$GITHUB_WORKSPACE/data":/app/data \
          -p 8501:8501 \
          personal-logs:latest